# Generated by Django 4.2 on 2023-05-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
