# Generated by Django 4.2 on 2023-05-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='username',
            new_name='user_id',
        ),
    ]
